# -*- coding: utf-8 -*-
"""lab-10 pos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qtxQT0PnxNostV5iMPYLsJtlZiYKB4P4
"""

import pandas as pd

df=pd.read_csv('sales_data_sample.csv',encoding='unicode_escape')
df

c= df.groupby(['PRODUCTLINE'])[['QUANTITYORDERED', 'SALES']].sum().reset_index()
c

cols = ['CUSTOMERNAME','ORDERDATE','ORDERNUMBER','SALES']
df = df[cols]
df.sort_values('ORDERDATE')

df.plot(kind='bar')

df.hist(bins=3)

import pandas as pd
import numpy as np
import seaborn as sns

sns.set_style('dark')

df1=pd.read_csv('sales_data_sample.csv',encoding='unicode_escape')
df1['SALES'].plot(kind='hist')

import matplotlib.pyplot as plt
plt.scatter(df1['QUANTITYORDERED'],df1['SALES'])
plt.show()

set=df1
corrgraph= set.corr()
sns.heatmap(corrgraph, annot = True)
plt.show()

df2=c['SALES']/4

df2

m= df.groupby(['YEAR_ID','MONTH_ID'])['SALES'].sum().reset_index()

y3= m[m['YEAR_ID'] == 2003]
y3

y3.hist(bins=3)

d=df[df['YEAR_ID'] == 2003]
d

df['SALES'].sum()